### PR TITLE
OS Windows support

### PR DESCRIPTION
**Pull request by brookite**
What has been done:
-Removed plumbum dependency (now pyfzf uses only standard library modules)
-Added OS Windows support
-Ability to specify fzf executable path

This commit fixes issue #8

### CODE REVIEW

**Comment by brookite** [comment]
@nk412 Could you take a look please?

**Comment by nk412** [comment]
Thank you very much @brookite for this.

I'll have a look at this tonight, and run some tests (still missing 😬)
If all's good, I'll merge and update the PyPI index.

**Comment by brookite** [comment]
Ok, I fastly tested the module on Windows and Linux, but i wasn't check it on mac OS. I have not ability to do this. Probably this commit need more thorough testing, because I'm afraid that side effects may occur due to the refusal to use the plumbum

**Comment by nk412** [comment]
@brookite can you please open another PR for the `release` branch instead of `master`? Have a couple of smaller tweaks I'd like to push with the next release to PyPI.

**Pull request closed without merging**
